# coding: utf-8

"""
    MeshDB Data API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pymeshdb.models.node_edit import NodeEdit

class TestNodeEdit(unittest.TestCase):
    """NodeEdit unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NodeEdit:
        """Test NodeEdit
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NodeEdit`
        """
        model = NodeEdit()
        if include_optional:
            return NodeEdit(
                id = '',
                buildings = [
                    pymeshdb.models.node_buildings_inner.Node_buildings_inner(
                        id = '', )
                    ],
                devices = [
                    pymeshdb.models.node_devices_inner.Node_devices_inner(
                        id = '', )
                    ],
                installs = [
                    pymeshdb.models.building_installs_inner.Building_installs_inner(
                        id = '', 
                        install_number = 56, )
                    ],
                network_number = 56,
                name = '',
                status = 'Inactive',
                type = 'Standard',
                latitude = 1.337,
                longitude = 1.337,
                altitude = 1.337,
                install_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                abandon_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                notes = ''
            )
        else:
            return NodeEdit(
                buildings = [
                    pymeshdb.models.node_buildings_inner.Node_buildings_inner(
                        id = '', )
                    ],
                devices = [
                    pymeshdb.models.node_devices_inner.Node_devices_inner(
                        id = '', )
                    ],
                installs = [
                    pymeshdb.models.building_installs_inner.Building_installs_inner(
                        id = '', 
                        install_number = 56, )
                    ],
                network_number = 56,
                status = 'Inactive',
                latitude = 1.337,
                longitude = 1.337,
        )
        """

    def testNodeEdit(self):
        """Test NodeEdit"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
