# coding: utf-8

"""
    MeshDB Data API

    Programmatic access to mesh core data, detailing our installs, members, etc.   To use an authorization token, use the \"Authorize\" button, and under \"tokenAuth\" enter `Token ` before the content of your token, like this: `Token xxxyyyyyzzz`  If you have username/password credentials (like those used on the admin UI) you can login via the admin UI or [DRF login page](/auth/login/?next=/api-docs/swagger/)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pymeshdb.api.nodes_api import NodesApi


class TestNodesApi(unittest.TestCase):
    """NodesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = NodesApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_nodes_create(self) -> None:
        """Test case for api_v1_nodes_create

        """
        pass

    def test_api_v1_nodes_destroy(self) -> None:
        """Test case for api_v1_nodes_destroy

        """
        pass

    def test_api_v1_nodes_destroy2(self) -> None:
        """Test case for api_v1_nodes_destroy2

        """
        pass

    def test_api_v1_nodes_list(self) -> None:
        """Test case for api_v1_nodes_list

        """
        pass

    def test_api_v1_nodes_lookup_list(self) -> None:
        """Test case for api_v1_nodes_lookup_list

        """
        pass

    def test_api_v1_nodes_partial_update(self) -> None:
        """Test case for api_v1_nodes_partial_update

        """
        pass

    def test_api_v1_nodes_partial_update2(self) -> None:
        """Test case for api_v1_nodes_partial_update2

        """
        pass

    def test_api_v1_nodes_retrieve(self) -> None:
        """Test case for api_v1_nodes_retrieve

        """
        pass

    def test_api_v1_nodes_retrieve2(self) -> None:
        """Test case for api_v1_nodes_retrieve2

        """
        pass

    def test_api_v1_nodes_update(self) -> None:
        """Test case for api_v1_nodes_update

        """
        pass

    def test_api_v1_nodes_update2(self) -> None:
        """Test case for api_v1_nodes_update2

        """
        pass


if __name__ == '__main__':
    unittest.main()
