# coding: utf-8

"""
    MeshDB Data API

    Programmatic access to mesh core data, detailing our installs, members, etc.   To use an authorization token, use the \"Authorize\" button, and under \"tokenAuth\" enter `Token ` before the content of your token, like this: `Token xxxyyyyyzzz`  If you have username/password credentials (like those used on the admin UI) you can login via the admin UI or [DRF login page](/auth/login/?next=/api-docs/swagger/)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pymeshdb.models.install import Install

class TestInstall(unittest.TestCase):
    """Install unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Install:
        """Test Install
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Install`
        """
        model = Install()
        if include_optional:
            return Install(
                id = '',
                install_number = 56,
                status = 'Request Received',
                ticket_number = '',
                request_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                install_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                abandon_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                unit = '',
                roof_access = True,
                referral = '',
                notes = '',
                diy = True,
                node = pymeshdb.models.install_node.Install_node(
                    id = '', 
                    network_number = -2147483648, ),
                building = pymeshdb.models.install_building.Install_building(
                    id = '', ),
                member = pymeshdb.models.install_member.Install_member(
                    id = '', )
            )
        else:
            return Install(
                id = '',
                install_number = 56,
                status = 'Request Received',
                request_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                building = pymeshdb.models.install_building.Install_building(
                    id = '', ),
                member = pymeshdb.models.install_member.Install_member(
                    id = '', ),
        )
        """

    def testInstall(self):
        """Test Install"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
