# coding: utf-8

"""
    MeshDB Data API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pymeshdb.api.buildings_api import BuildingsApi


class TestBuildingsApi(unittest.TestCase):
    """BuildingsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BuildingsApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_buildings_create(self) -> None:
        """Test case for api_v1_buildings_create

        """
        pass

    def test_api_v1_buildings_destroy(self) -> None:
        """Test case for api_v1_buildings_destroy

        """
        pass

    def test_api_v1_buildings_list(self) -> None:
        """Test case for api_v1_buildings_list

        """
        pass

    def test_api_v1_buildings_lookup_list(self) -> None:
        """Test case for api_v1_buildings_lookup_list

        """
        pass

    def test_api_v1_buildings_partial_update(self) -> None:
        """Test case for api_v1_buildings_partial_update

        """
        pass

    def test_api_v1_buildings_retrieve(self) -> None:
        """Test case for api_v1_buildings_retrieve

        """
        pass

    def test_api_v1_buildings_update(self) -> None:
        """Test case for api_v1_buildings_update

        """
        pass


if __name__ == '__main__':
    unittest.main()
