# coding: utf-8

"""
    MeshDB Data API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pymeshdb.models.error_response_invalid_addr import ErrorResponseInvalidAddr

class TestErrorResponseInvalidAddr(unittest.TestCase):
    """ErrorResponseInvalidAddr unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ErrorResponseInvalidAddr:
        """Test ErrorResponseInvalidAddr
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ErrorResponseInvalidAddr`
        """
        model = ErrorResponseInvalidAddr()
        if include_optional:
            return ErrorResponseInvalidAddr(
                detail = ''
            )
        else:
            return ErrorResponseInvalidAddr(
                detail = '',
        )
        """

    def testErrorResponseInvalidAddr(self):
        """Test ErrorResponseInvalidAddr"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
