# coding: utf-8

"""
    MeshDB Data API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pymeshdb.models.type1bf_enum import Type1bfEnum

class TestType1bfEnum(unittest.TestCase):
    """Type1bfEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testType1bfEnum(self):
        """Test Type1bfEnum"""
        # inst = Type1bfEnum()

if __name__ == '__main__':
    unittest.main()
