# coding: utf-8

"""
    MeshDB Data API

    Programmatic access to mesh core data, detailing our installs, members, etc.   To use an authorization token, use the \"Authorize\" button, and under \"tokenAuth\" enter `Token ` before the content of your token, like this: `Token xxxyyyyyzzz`  If you have username/password credentials (like those used on the admin UI) you can login via the admin UI or [DRF login page](/auth/login/?next=/api-docs/swagger/)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pymeshdb.models.blank_enum import BlankEnum

class TestBlankEnum(unittest.TestCase):
    """BlankEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlankEnum(self):
        """Test BlankEnum"""
        # inst = BlankEnum()

if __name__ == '__main__':
    unittest.main()
