# coding: utf-8

"""
    MeshDB Data API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pymeshdb.models.los import LOS

class TestLOS(unittest.TestCase):
    """LOS unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LOS:
        """Test LOS
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LOS`
        """
        model = LOS()
        if include_optional:
            return LOS(
                id = '',
                analysis_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                source = 'Human Annotated',
                notes = '',
                from_building = pymeshdb.models.los_from_building.LOS_from_building(
                    id = '', ),
                to_building = pymeshdb.models.los_from_building.LOS_from_building(
                    id = '', )
            )
        else:
            return LOS(
                id = '',
                source = 'Human Annotated',
                from_building = pymeshdb.models.los_from_building.LOS_from_building(
                    id = '', ),
                to_building = pymeshdb.models.los_from_building.LOS_from_building(
                    id = '', ),
        )
        """

    def testLOS(self):
        """Test LOS"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
