# coding: utf-8

"""
    MeshDB Data API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pymeshdb.api.website_map_data_api import WebsiteMapDataApi


class TestWebsiteMapDataApi(unittest.TestCase):
    """WebsiteMapDataApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WebsiteMapDataApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_mapdata_kiosks_retrieve(self) -> None:
        """Test case for api_v1_mapdata_kiosks_retrieve

        Proxy for the city of new york LinkNYC kisok location dataset. Output in a JSON format that is compatible with the website map. (Warning: This endpoint is a legacy format and may be deprecated/removed in the future)
        """
        pass

    def test_api_v1_mapdata_links_list(self) -> None:
        """Test case for api_v1_mapdata_links_list

        Complete list of all Links, unpaginated, in the format expected by the website map. (Warning: This endpoint is a legacy format and may be deprecated/removed in the future)
        """
        pass

    def test_api_v1_mapdata_nodes_list(self) -> None:
        """Test case for api_v1_mapdata_nodes_list

        Complete list of all \"Nodes\" (mostly Installs with some fake installs generated to solve NN re-use), unpaginated, in the format expected by the website map. (Warning: This endpoint is a legacy format and may be deprecated/removed in the future)
        """
        pass

    def test_api_v1_mapdata_sectors_list(self) -> None:
        """Test case for api_v1_mapdata_sectors_list

        Complete list of all Sectors, unpaginated, in the format expected by the website map. (Warning: This endpoint is a legacy format and may be deprecated/removed in the future)
        """
        pass


if __name__ == '__main__':
    unittest.main()
