# coding: utf-8

"""
    MeshDB Data API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pymeshdb.models.source_enum import SourceEnum

class TestSourceEnum(unittest.TestCase):
    """SourceEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSourceEnum(self):
        """Test SourceEnum"""
        # inst = SourceEnum()

if __name__ == '__main__':
    unittest.main()
