# coding: utf-8

"""
    MeshDB Data API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pymeshdb.models.address_truth_sources_enum import AddressTruthSourcesEnum

class TestAddressTruthSourcesEnum(unittest.TestCase):
    """AddressTruthSourcesEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddressTruthSourcesEnum(self):
        """Test AddressTruthSourcesEnum"""
        # inst = AddressTruthSourcesEnum()

if __name__ == '__main__':
    unittest.main()
