# coding: utf-8

"""
    MeshDB Data API

    Programmatic access to mesh core data, detailing our installs, members, etc.   To use an authorization token, use the \"Authorize\" button, and under \"tokenAuth\" enter `Token ` before the content of your token, like this: `Token xxxyyyyyzzz`  If you have username/password credentials (like those used on the admin UI) you can login via the admin UI or [DRF login page](/auth/login/?next=/api-docs/swagger/)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pymeshdb.models.paginated_query_form_list import PaginatedQueryFormList

class TestPaginatedQueryFormList(unittest.TestCase):
    """PaginatedQueryFormList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedQueryFormList:
        """Test PaginatedQueryFormList
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedQueryFormList`
        """
        model = PaginatedQueryFormList()
        if include_optional:
            return PaginatedQueryFormList(
                count = 123,
                next = 'http://api.example.org/accounts/?page=4',
                previous = 'http://api.example.org/accounts/?page=2',
                results = [
                    pymeshdb.models.query_form.QueryForm(
                        install_number = 56, 
                        street_address = '', 
                        unit = '', 
                        city = '', 
                        state = '', 
                        zip_code = '', 
                        name = '', 
                        phone_number = '', 
                        additional_phone_numbers = [
                            ''
                            ], 
                        primary_email_address = '', 
                        stripe_email_address = '', 
                        additional_email_addresses = [
                            ''
                            ], 
                        notes = '', 
                        network_number = 56, 
                        status = null, )
                    ]
            )
        else:
            return PaginatedQueryFormList(
                count = 123,
                results = [
                    pymeshdb.models.query_form.QueryForm(
                        install_number = 56, 
                        street_address = '', 
                        unit = '', 
                        city = '', 
                        state = '', 
                        zip_code = '', 
                        name = '', 
                        phone_number = '', 
                        additional_phone_numbers = [
                            ''
                            ], 
                        primary_email_address = '', 
                        stripe_email_address = '', 
                        additional_email_addresses = [
                            ''
                            ], 
                        notes = '', 
                        network_number = 56, 
                        status = null, )
                    ],
        )
        """

    def testPaginatedQueryFormList(self):
        """Test PaginatedQueryFormList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
