# coding: utf-8

"""
    MeshDB Data API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pymeshdb.models.paginated_building_list import PaginatedBuildingList

class TestPaginatedBuildingList(unittest.TestCase):
    """PaginatedBuildingList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedBuildingList:
        """Test PaginatedBuildingList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedBuildingList`
        """
        model = PaginatedBuildingList()
        if include_optional:
            return PaginatedBuildingList(
                count = 123,
                next = 'http://api.example.org/accounts/?page=4',
                previous = 'http://api.example.org/accounts/?page=2',
                results = [
                    pymeshdb.models.building.Building(
                        id = '', 
                        installs = [
                            pymeshdb.models.building_installs_inner.Building_installs_inner(
                                id = '', 
                                install_number = 56, )
                            ], 
                        bin = 0, 
                        street_address = '', 
                        city = '', 
                        state = '', 
                        zip_code = '', 
                        address_truth_sources = [
                            'OSMNominatim'
                            ], 
                        latitude = 1.337, 
                        longitude = 1.337, 
                        altitude = 1.337, 
                        notes = '', 
                        panoramas = [
                            ''
                            ], 
                        primary_node = pymeshdb.models.building_primary_node.Building_primary_node(
                            id = '', 
                            network_number = -2147483648, ), 
                        nodes = [
                            pymeshdb.models.building_nodes_inner.Building_nodes_inner(
                                id = '', 
                                network_number = -2147483648, )
                            ], )
                    ]
            )
        else:
            return PaginatedBuildingList(
                count = 123,
                results = [
                    pymeshdb.models.building.Building(
                        id = '', 
                        installs = [
                            pymeshdb.models.building_installs_inner.Building_installs_inner(
                                id = '', 
                                install_number = 56, )
                            ], 
                        bin = 0, 
                        street_address = '', 
                        city = '', 
                        state = '', 
                        zip_code = '', 
                        address_truth_sources = [
                            'OSMNominatim'
                            ], 
                        latitude = 1.337, 
                        longitude = 1.337, 
                        altitude = 1.337, 
                        notes = '', 
                        panoramas = [
                            ''
                            ], 
                        primary_node = pymeshdb.models.building_primary_node.Building_primary_node(
                            id = '', 
                            network_number = -2147483648, ), 
                        nodes = [
                            pymeshdb.models.building_nodes_inner.Building_nodes_inner(
                                id = '', 
                                network_number = -2147483648, )
                            ], )
                    ],
        )
        """

    def testPaginatedBuildingList(self):
        """Test PaginatedBuildingList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
