# coding: utf-8

"""
    MeshDB Data API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pymeshdb.models.paginated_install_fee_billing_datum_list import PaginatedInstallFeeBillingDatumList

class TestPaginatedInstallFeeBillingDatumList(unittest.TestCase):
    """PaginatedInstallFeeBillingDatumList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedInstallFeeBillingDatumList:
        """Test PaginatedInstallFeeBillingDatumList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedInstallFeeBillingDatumList`
        """
        model = PaginatedInstallFeeBillingDatumList()
        if include_optional:
            return PaginatedInstallFeeBillingDatumList(
                count = 123,
                next = 'http://api.example.org/accounts/?page=4',
                previous = 'http://api.example.org/accounts/?page=2',
                results = [
                    pymeshdb.models.install_fee_billing_datum.InstallFeeBillingDatum(
                        id = '', 
                        status = null, 
                        billing_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        invoice_number = '', 
                        notes = '', 
                        install = pymeshdb.models.install_fee_billing_datum_install.InstallFeeBillingDatum_install(
                            id = '', 
                            install_number = 56, ), )
                    ]
            )
        else:
            return PaginatedInstallFeeBillingDatumList(
                count = 123,
                results = [
                    pymeshdb.models.install_fee_billing_datum.InstallFeeBillingDatum(
                        id = '', 
                        status = null, 
                        billing_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        invoice_number = '', 
                        notes = '', 
                        install = pymeshdb.models.install_fee_billing_datum_install.InstallFeeBillingDatum_install(
                            id = '', 
                            install_number = 56, ), )
                    ],
        )
        """

    def testPaginatedInstallFeeBillingDatumList(self):
        """Test PaginatedInstallFeeBillingDatumList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
