# coding: utf-8

"""
    MeshDB Data API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pymeshdb.models.link_from_device import LinkFromDevice

class TestLinkFromDevice(unittest.TestCase):
    """LinkFromDevice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LinkFromDevice:
        """Test LinkFromDevice
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LinkFromDevice`
        """
        model = LinkFromDevice()
        if include_optional:
            return LinkFromDevice(
                id = ''
            )
        else:
            return LinkFromDevice(
        )
        """

    def testLinkFromDevice(self):
        """Test LinkFromDevice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
