# coding: utf-8

"""
    MeshDB Data API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pymeshdb.api.user_forms_api import UserFormsApi


class TestUserFormsApi(unittest.TestCase):
    """UserFormsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UserFormsApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_join_create(self) -> None:
        """Test case for api_v1_join_create

        Register a new request for a potential mesh Install. Used by the join form posted on the nycmesh.net website
        """
        pass

    def test_api_v1_nn_assign_create(self) -> None:
        """Test case for api_v1_nn_assign_create

        Assign a network number to a given Install object. Used by the NN Assignment form
        """
        pass


if __name__ == '__main__':
    unittest.main()
