# coding: utf-8

"""
    MeshDB Data API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pymeshdb.models.status4ff_enum import Status4ffEnum

class TestStatus4ffEnum(unittest.TestCase):
    """Status4ffEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatus4ffEnum(self):
        """Test Status4ffEnum"""
        # inst = Status4ffEnum()

if __name__ == '__main__':
    unittest.main()
