# coding: utf-8

"""
    MeshDB Data API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pymeshdb.models.disambiguate_number_supporting_data import DisambiguateNumberSupportingData

class TestDisambiguateNumberSupportingData(unittest.TestCase):
    """DisambiguateNumberSupportingData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DisambiguateNumberSupportingData:
        """Test DisambiguateNumberSupportingData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DisambiguateNumberSupportingData`
        """
        model = DisambiguateNumberSupportingData()
        if include_optional:
            return DisambiguateNumberSupportingData(
                exact_match_install = pymeshdb.models.install_nested_ref.InstallNestedRef(
                    install_number = 56, 
                    id = '', 
                    node = pymeshdb.models.install_node.Install_node(
                        id = '', 
                        network_number = -2147483648, ), ),
                exact_match_recycled_install = pymeshdb.models.install_nested_ref.InstallNestedRef(
                    install_number = 56, 
                    id = '', 
                    node = pymeshdb.models.install_node.Install_node(
                        id = '', 
                        network_number = -2147483648, ), ),
                exact_match_node = pymeshdb.models.disambiguate_number_supporting_data_exact_match_node.DisambiguateNumberSupportingData_exact_match_node(
                    id = '', 
                    network_number = -2147483648, )
            )
        else:
            return DisambiguateNumberSupportingData(
                exact_match_install = pymeshdb.models.install_nested_ref.InstallNestedRef(
                    install_number = 56, 
                    id = '', 
                    node = pymeshdb.models.install_node.Install_node(
                        id = '', 
                        network_number = -2147483648, ), ),
                exact_match_recycled_install = pymeshdb.models.install_nested_ref.InstallNestedRef(
                    install_number = 56, 
                    id = '', 
                    node = pymeshdb.models.install_node.Install_node(
                        id = '', 
                        network_number = -2147483648, ), ),
                exact_match_node = pymeshdb.models.disambiguate_number_supporting_data_exact_match_node.DisambiguateNumberSupportingData_exact_match_node(
                    id = '', 
                    network_number = -2147483648, ),
        )
        """

    def testDisambiguateNumberSupportingData(self):
        """Test DisambiguateNumberSupportingData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
