# coding: utf-8

"""
    MeshDB Data API

    Programmatic access to mesh core data, detailing our installs, members, etc.   To use an authorization token, use the \"Authorize\" button, and under \"tokenAuth\" enter `Token ` before the content of your token, like this: `Token xxxyyyyyzzz`  If you have username/password credentials (like those used on the admin UI) you can login via the admin UI or [DRF login page](/auth/login/?next=/api-docs/swagger/)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pymeshdb.models.los_from_building import LOSFromBuilding
from pymeshdb.models.source_enum import SourceEnum
from typing import Optional, Set
from typing_extensions import Self

class LOS(BaseModel):
    """
    A  ModelSerializer MixIn which sets `NestedKeyObjectRelatedField` as the default field class to use for the foreign key fields
    """ # noqa: E501
    id: StrictStr
    analysis_date: Optional[date] = Field(default=None, description="The date we conducted the analysis that concluded this LOS exists. Important since new buildings might have been built which block the LOS after this date")
    source: SourceEnum = Field(description="The source of information that tells us this LOS exists  * `Human Annotated` - Human Annotated * `Existing Link` - Existing Link")
    notes: Optional[StrictStr] = Field(default=None, description="A free-form text description of this LOS, to track any additional information.")
    from_building: LOSFromBuilding
    to_building: LOSFromBuilding
    __properties: ClassVar[List[str]] = ["id", "analysis_date", "source", "notes", "from_building", "to_building"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LOS from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of from_building
        if self.from_building:
            _dict['from_building'] = self.from_building.to_dict()
        # override the default output from pydantic by calling `to_dict()` of to_building
        if self.to_building:
            _dict['to_building'] = self.to_building.to_dict()
        # set to None if analysis_date (nullable) is None
        # and model_fields_set contains the field
        if self.analysis_date is None and "analysis_date" in self.model_fields_set:
            _dict['analysis_date'] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict['notes'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LOS from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "analysis_date": obj.get("analysis_date"),
            "source": obj.get("source"),
            "notes": obj.get("notes"),
            "from_building": LOSFromBuilding.from_dict(obj["from_building"]) if obj.get("from_building") is not None else None,
            "to_building": LOSFromBuilding.from_dict(obj["to_building"]) if obj.get("to_building") is not None else None
        })
        return _obj


