# coding: utf-8

"""
    MeshDB Data API

    Programmatic access to mesh core data, detailing our installs, members, etc.   To use an authorization token, use the \"Authorize\" button, and under \"tokenAuth\" enter `Token ` before the content of your token, like this: `Token xxxyyyyyzzz`  If you have username/password credentials (like those used on the admin UI) you can login via the admin UI or [DRF login page](/auth/login/?next=/api-docs/swagger/)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from pymeshdb.models.building_installs_inner import BuildingInstallsInner
from pymeshdb.models.node_buildings_inner import NodeBuildingsInner
from pymeshdb.models.node_devices_inner import NodeDevicesInner
from pymeshdb.models.status2a6_enum import Status2a6Enum
from pymeshdb.models.type_b10_enum import TypeB10Enum
from typing import Optional, Set
from typing_extensions import Self

class Node(BaseModel):
    """
    A  ModelSerializer MixIn which sets `NestedKeyObjectRelatedField` as the default field class to use for the foreign key fields
    """ # noqa: E501
    id: Optional[StrictStr] = None
    buildings: List[NodeBuildingsInner]
    devices: List[NodeDevicesInner]
    installs: List[BuildingInstallsInner]
    network_number: Optional[Annotated[int, Field(le=8192, strict=True, ge=-2147483648)]] = None
    name: Optional[StrictStr] = Field(default=None, description="The colloquial name of this node used among mesh volunteers, if applicable")
    status: Status2a6Enum = Field(description="The current status of this Node  * `Inactive` - Inactive * `Active` - Active * `Planned` - Planned")
    type: Optional[TypeB10Enum] = Field(default=None, description="The type of node this is, controls the icon used on the network map  * `Standard` - Standard * `Hub` - Hub * `Supernode` - Supernode * `POP` - Pop * `AP` - Ap * `Remote` - Remote")
    latitude: Union[StrictFloat, StrictInt] = Field(description="Approximate Node latitude in decimal degrees (this will match one of the attached Building objects in most cases, but has been manually moved around in some cases to more accurately reflect node location)")
    longitude: Union[StrictFloat, StrictInt] = Field(description="Approximate Node longitude in decimal degrees (this will match one of the attached Building objects in most cases, but has been manually moved around in some cases to more accurately reflect node location)")
    altitude: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Approximate Node altitude in \"absolute\" meters above mean sea level (this will match one of the attached Building objects in most cases, but has been manually moved around in some cases to more accurately reflect node location)")
    install_date: Optional[date] = Field(default=None, description="The date the first Install or Device associated with this Node became active on the mesh")
    abandon_date: Optional[date] = Field(default=None, description="The date the last Install or Device associated with this Node was abandoned, unplugged, or removed from service")
    notes: Optional[StrictStr] = Field(default=None, description="A free-form text description of this Node, to track any additional information. For Nodes imported from the spreadsheet, this starts with a formatted block of information about the import process and original spreadsheet data. However this structure can be changed by admins at any time and should not be relied on by automated systems. ")
    __properties: ClassVar[List[str]] = ["id", "buildings", "devices", "installs", "network_number", "name", "status", "type", "latitude", "longitude", "altitude", "install_date", "abandon_date", "notes"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Node from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "buildings",
            "devices",
            "installs",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in buildings (list)
        _items = []
        if self.buildings:
            for _item in self.buildings:
                if _item:
                    _items.append(_item.to_dict())
            _dict['buildings'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in devices (list)
        _items = []
        if self.devices:
            for _item in self.devices:
                if _item:
                    _items.append(_item.to_dict())
            _dict['devices'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in installs (list)
        _items = []
        if self.installs:
            for _item in self.installs:
                if _item:
                    _items.append(_item.to_dict())
            _dict['installs'] = _items
        # set to None if network_number (nullable) is None
        # and model_fields_set contains the field
        if self.network_number is None and "network_number" in self.model_fields_set:
            _dict['network_number'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if altitude (nullable) is None
        # and model_fields_set contains the field
        if self.altitude is None and "altitude" in self.model_fields_set:
            _dict['altitude'] = None

        # set to None if install_date (nullable) is None
        # and model_fields_set contains the field
        if self.install_date is None and "install_date" in self.model_fields_set:
            _dict['install_date'] = None

        # set to None if abandon_date (nullable) is None
        # and model_fields_set contains the field
        if self.abandon_date is None and "abandon_date" in self.model_fields_set:
            _dict['abandon_date'] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict['notes'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Node from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "buildings": [NodeBuildingsInner.from_dict(_item) for _item in obj["buildings"]] if obj.get("buildings") is not None else None,
            "devices": [NodeDevicesInner.from_dict(_item) for _item in obj["devices"]] if obj.get("devices") is not None else None,
            "installs": [BuildingInstallsInner.from_dict(_item) for _item in obj["installs"]] if obj.get("installs") is not None else None,
            "network_number": obj.get("network_number"),
            "name": obj.get("name"),
            "status": obj.get("status"),
            "type": obj.get("type"),
            "latitude": obj.get("latitude"),
            "longitude": obj.get("longitude"),
            "altitude": obj.get("altitude"),
            "install_date": obj.get("install_date"),
            "abandon_date": obj.get("abandon_date"),
            "notes": obj.get("notes")
        })
        return _obj


